name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy stack
        run: |
          set -e

          echo "📂 Workspace:"
          cd $GITHUB_WORKSPACE
          pwd

          echo "📦 Files:"
          ls -la

          echo "🧹 Stopping old containers"
          docker compose down || true

          echo "🚀 Starting services"
          docker compose up -d

          echo "📊 Running containers"
          docker ps